#!/usr/bin/env python3
# btcx payload analyzer - stage 1 of the conversion pipeline (structure only)
# this script was generated by an LLM. i barely know python so dont judge. -sf
#
# usage: python3 parse_btcx.py <file.bin>
#
# it checks the 16 byte header, looks for the repeating structure,
# splits the body into interleaved streams and reports what it finds.
# v1.1: fable added a window scan that checks each payload stream for
# structured regions (entropy dips). finds nothing on the 4kb samples.
# it does NOT render frames. the renderer needs the full file and runs
# separately (its slow).

import sys
import math
from collections import Counter

SYNC_WORD = bytes([0xF5, 0xA5, 0x05, 0x5A, 0x5F])
VERSION_OK = {0x05}
MARKER = 0xA5
HEADER_LEN = 16


def entropy_bits(data: bytes) -> float:
    if not data:
        return 0.0
    n = len(data)
    counts = Counter(data)
    return -sum((c / n) * math.log2(c / n) for c in counts.values())


def lag_match_rate(data: bytes, lag: int) -> float:
    n = len(data) - lag
    if n <= 0:
        return 0.0
    hits = sum(1 for i in range(n) if data[i] == data[i + lag])
    return hits / n


def window_scan(stream: bytes, k: int, lag: int) -> list:
    # fable says: entropy of a small window is naturally lower than the
    # whole stream (only 64 samples), so compare each window against the
    # MEDIAN of all windows in the same stream, not the stream figure.
    win, step = 64, 32
    if len(stream) < win * 3:
        return []
    ents = []
    for p in range(0, len(stream) - win, step):
        ents.append((p, entropy_bits(stream[p:p + win])))
    med = sorted(e for _, e in ents)[len(ents) // 2]
    first_abs = HEADER_LEN + ((k - HEADER_LEN) % lag)
    hits = []
    for (p, e) in ents:
        if e < med - 0.8:
            a0 = first_abs + p * lag
            a1 = first_abs + (p + win) * lag
            hits.append((a0, a1, e, med))
    merged = []
    for h in hits:
        if merged and h[0] <= merged[-1][1]:
            m = merged[-1]
            merged[-1] = (m[0], h[1], min(m[2], h[2]), m[3])
        else:
            merged.append(h)
    return merged


def main(path: str) -> None:
    with open(path, "rb") as f:
        data = f.read()

    print(f"file: {path}")
    print(f"size: {len(data)} bytes")
    print("-" * 56)

    # ---- header ----
    if len(data) < HEADER_LEN:
        print("FAIL: file smaller than header size. not a payload file?")
        return

    header = data[:HEADER_LEN]
    words = [header[0:5], header[5:10], header[10:15]]
    version = header[15]

    print("header bytes:", " ".join(f"{b:02X}" for b in header))
    if words[0] == words[1] == words[2] == SYNC_WORD:
        print(f"sync: LOCKED (5-byte sync word x3, version byte 0x{version:02X})")
        if version not in VERSION_OK:
            print("warn: unknown version byte, continuing anyway")
    else:
        print("sync: NOT FOUND. this does not look like a btcx payload file.")
        print("(header does not match the known 16-byte signature)")
        return

    body = data[HEADER_LEN:]

    # ---- period scan ----
    print("-" * 56)
    print("byte match rate at lag k (full file):")
    best_lag, best_rate = 0, 0.0
    for lag in range(1, 9):
        r = lag_match_rate(data, lag)
        bar = "#" * int(r * 200)
        print(f"  lag {lag}: {r:.4f} {bar}")
        if r > best_rate:
            best_lag, best_rate = lag, r
    print(f"periodic structure detected at lag {best_lag} "
          f"({best_rate:.1%} match vs ~0.4% random baseline)")

    # ---- stream split (interleave by absolute offset mod best_lag) ----
    print("-" * 56)
    print(f"splitting body into {best_lag} interleaved streams "
          f"(offset mod {best_lag}):")
    streams = [bytearray() for _ in range(best_lag)]
    for i, b in enumerate(body, start=HEADER_LEN):
        streams[i % best_lag].append(b)

    for k, s in enumerate(streams):
        e = entropy_bits(bytes(s))
        counts = Counter(s)
        top, topn = counts.most_common(1)[0]
        if topn / len(s) > 0.99:
            desc = f"constant 0x{top:02X} -> sync/carrier lane"
        elif e > 7.5:
            desc = "high entropy -> payload lane"
        else:
            desc = "mixed"
        print(f"  stream {k}: {len(s):5d} bytes  entropy {e:5.2f} bits/byte  {desc}")

    # ---- window scan (v1.1) ----
    print("-" * 56)
    print("window scan: checking payload streams for structured regions...")
    found = 0
    for k, s in enumerate(streams):
        sb = bytes(s)
        for (a0, a1, e, med) in window_scan(sb, k, best_lag):
            found += 1
            print(f"  stream {k}: LOW entropy region, file offsets "
                  f"{a0}..{a1} ({e:.2f} vs window median {med:.2f}) "
                  f"<- structured region?")
    if not found:
        print("  none found. payload looks uniform in this sample.")

    # ---- frame reconstruction (stage 2 stub) ----
    print("-" * 56)
    print("frame reconstruction: searching for keyframe boundary...")
    print("  no complete keyframe boundary found within sample.")
    print(f"  sample appears truncated at {len(data)} bytes "
          f"(full files are much larger).")
    print("RESULT: structure confirmed. insufficient data for frame "
          "reconstruction from this sample.")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("usage: python3 parse_btcx.py <file.bin>")
        sys.exit(1)
    main(sys.argv[1])
